// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKhBDCP2-cxxd41RJbg3hR39poFLzqId0',
    appId: '1:298073330610:web:b8f29706abdc4dd3f08aab',
    messagingSenderId: '298073330610',
    projectId: 'rolebasedlogin-c976c',
    authDomain: 'rolebasedlogin-c976c.firebaseapp.com',
    storageBucket: 'rolebasedlogin-c976c.appspot.com',
    measurementId: 'G-H0641WMZ2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVJ2AooUvEeKit8zejf2sL568szsIWzWY',
    appId: '1:298073330610:android:bfdcaeb4b50cf118f08aab',
    messagingSenderId: '298073330610',
    projectId: 'rolebasedlogin-c976c',
    storageBucket: 'rolebasedlogin-c976c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA1FXonoHEYHq5IUzCF3xFMNvtCLta1as',
    appId: '1:298073330610:ios:feef2433ffe98c99f08aab',
    messagingSenderId: '298073330610',
    projectId: 'rolebasedlogin-c976c',
    storageBucket: 'rolebasedlogin-c976c.appspot.com',
    iosClientId: '298073330610-895bt3bi9fomaspcbkurauflqmn8qcue.apps.googleusercontent.com',
    iosBundleId: 'com.example.project9',
  );
}
